/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Modelo.konexion;
import Ventanas.VComedor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;

public class pagarCuenta_1 extends javax.swing.JFrame {
    konexion con = new konexion();
    Connection cn = con.konexion();
    PreparedStatement sql;
    ResultSet rs;
    private VComedor comedor;
    private double pagoEfectivo = 0.0;
    private double pagoTarjeta = 0.0;
    private double pagoTransferencia = 0.0;
    
    public pagarCuenta_1() {
        initComponents();
        this.setLocationRelativeTo(null);
        moverAVentas();
        this.comedor=comedor;
    }
    
     public pagarCuenta_1(String mesaSeleccionada, double totalCuenta) {
        initComponents();

        // Inicializar los campos de la ventana con los valores correspondientes
        txtMesa.setText(mesaSeleccionada);
        txtTotal.setText(String.valueOf(totalCuenta));
    }
     
     private void calcularCambio() {
    try {
        // Obtener el total de la cuenta desde el campo de texto
        double totalCuenta = Double.parseDouble(txtTotal.getText());
        // Obtener las cantidades ingresadas
        pagoEfectivo = Double.parseDouble(txtEfectivo.getText());
        //pagoTarjeta = Double.parseDouble(txtTarjeta.getText());
        //pagoTransferencia = Double.parseDouble(txtTransferencia.getText());
        
        
        // Calcular el total pagado
        double totalPagado = pagoEfectivo + pagoTarjeta + pagoTransferencia;

        // Calcular el cambio
        double cambio = totalPagado - totalCuenta;

        // Mostrar el cambio en el campo correspondiente
        txtCambio.setText(String.valueOf(cambio));

        // Validar si la cantidad es insuficiente
        if (totalPagado < totalCuenta) {
            JOptionPane.showMessageDialog(this, "Cantidad insuficiente. ¡Debe ingresar un monto igual o mayor al total!");
        }
        // Acumular las cantidades de pago
        /*pagoEfectivo += nuevoPagoEfectivo-cambio;
        pagoTarjeta += nuevoPagoTarjeta;
        pagoTransferencia += nuevoPagoTransferencia;*/

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese cantidades válidas en los campos de pago.");
    }
}
     
     public double getPagoEfectivo() {
        return pagoEfectivo;
    }

    public double getPagoTarjeta() {
        return pagoTarjeta;
    }

    public double getPagoTransferencia() {
        return pagoTransferencia;
    }
     
     public void moverAVentas() {
        // Obtener el nombre de la mesa y el total desde los JLabel
        String nombreMesa = txtMesa.getText();
        double total = Double.parseDouble(txtTotal.getText());

        // Suponiendo que ya tienes la conexión
        Connection cn = con.konexion();

        if (cn != null) {
            try {
                // Borrar la fila de la tabla 'mesas'
                String sqlDelete = "DELETE FROM mesas WHERE Mesa = ?";
                try (PreparedStatement pstmtDelete = cn.prepareStatement(sqlDelete)) {
                    pstmtDelete.setString(1, nombreMesa);
                    pstmtDelete.executeUpdate();
                    
                }
                // Insertar la fila en la tabla 'ventas'
                String sqlInsert = "INSERT INTO ventas1 (Mesa, Total, efectivo,tarjeta,transferencia) VALUES (?,?,?,?, ?)";
                try (PreparedStatement pstmtInsert = cn.prepareStatement(sqlInsert)) {
                    pstmtInsert.setString(1, nombreMesa);
                    pstmtInsert.setDouble(2, total);
                    pstmtInsert.setDouble(3, pagoEfectivo - Double.parseDouble(txtCambio.getText())); // Restar el cambio al pago en efectivo
                    pstmtInsert.setDouble(4, pagoTarjeta);
                    pstmtInsert.setDouble(5, pagoTransferencia);
                    pstmtInsert.executeUpdate();
                    
                }

                System.out.println("Operación completada con éxito");

            } catch (SQLException e) {
                System.err.println("Error en la operación: " + e.getMessage());
            
            }
        }
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JTextField();
        txtTotal = new javax.swing.JLabel();
        txtMesa = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Mesa");

        jLabel2.setText("Total");

        jLabel3.setText("Pago");

        jLabel4.setText("Efectivo");

        txtEfectivo.setText("0.00");
        txtEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEfectivoActionPerformed(evt);
            }
        });

        txtTotal.setText(" ");

        txtMesa.setText(" ");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Cambio");

        txtCambio.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEfectivo)
                        .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesa))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotal))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCambio))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCancelar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEfectivoActionPerformed
             calcularCambio();
    }//GEN-LAST:event_txtEfectivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        moverAVentas();
        
        VComedor VComedor = new VComedor();
        VComedor.setVisible(true);
        this.dispose();
       
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        VComedor VComedor= new VComedor();
        VComedor.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagarCuenta_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagarCuenta_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagarCuenta_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagarCuenta_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagarCuenta_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCambio;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JLabel txtMesa;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
